c_compiler_version:            # [unix]
  - 11                         # [osx]
cxx_compiler_version:          # [unix]
  - 11                         # [osx]
numpy:
  - 1.16
python:
  - 2.7.* *_cpython
python_impl:
  - cpython
