c_compiler_version:            # [unix]
  - 9                          # [osx]
c_compiler_version:            # [unix]
  - 9                          # [osx]
numpy:
  - 1.16
python:
  - 2.7.* *_cpython
python_impl:
  - cpython
