c_compiler_version:            # [unix]
  - 9                          # [osx]
c_compiler_version:            # [unix]
  - 9                          # [osx]
numpy:
  - 1.16
python:
  - 2.7.* *_cpython
python_impl:
  - cpython
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.12                  # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.12                  # [osx and x86_64]
