package:
  name: wxpython
  version: 3.0.2.0

source:
  fn: wxPython-src-3.0.2.0.tar.bz2
  url: http://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2
  patches:
    - bitmap.patch
    - dataobj.patch
    - graphics.patch
    - mediactrl.patch
    - minmacos.patch
    - minmacos2.patch

build:
  number: 0
  skip: True  # [not osx]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: 'Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
