about: {home: 'http://www.wxpython.org/', license: wxWindows License, summary: Python
    wrapper around the wxWidgets Cross platform Graphical User Interface library}
build:
  entry_points: []
  features: []
  number: 0
  script: $RECIPE_DIR/build_osx.sh
  script_env: []
  skip: True  # [not osx]
  string: ''
  track_features: []
package: {name: wxpython, version: 3.0.2.0}
requirements:
  build: [python, setuptools]
  conflicts: []
  run: [python]
source:
  fn: wxPython-src-3.0.2.0.tar.bz2
  git_rev: ''
  md5: ''
  patches: []
  path: ''
  svn_rev: ''
  url: http://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/wxPython-src-3.0.2.0.tar.bz2
test:
  commands: []
  files: []
  imports: [wx]
  requires: []
